build file removal, dark mode changes (#185)
* Updates to delete build files, plus change it so the github include changes colour with dark mode

* Updates to do test/lint in the same file

* updates to add caching

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,13 +9,12 @@ on:
     branches:
         - main
         - preview
-
+permissions:
+  contents: read
 jobs:
     test:
         runs-on: ubuntu-latest
         name: Test
-        permissions:
-          contents: read
         steps:
             - name: Checkout code
               uses: actions/checkout@v6
@@ -26,7 +25,14 @@ jobs:
                   node-version-file: 'app/.nvmrc'
                   cache: 'npm'
                   cache-dependency-path: 'app/package-lock.json'
-
+            - name: Cache npm
+              uses: actions/cache@v5
+              with:
+                path: |
+                  ~/.npm
+                key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
+                restore-keys: |
+                  ${{ runner.os }}-node-
             - name: Install dependencies
               run: |
                 cd app
@@ -46,3 +52,35 @@ jobs:
               if: always()
               with:
                 paths: app/test-results/results.xml
+    lint:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v6
+        - name: Set up Node.js
+          uses: actions/setup-node@v6
+          with:
+              node-version-file: 'app/.nvmrc'
+              cache: 'npm'
+              cache-dependency-path: 'app/package-lock.json'
+        - name: Cache npm
+          uses: actions/cache@v5
+          with:
+            path: |
+              ~/.npm
+            key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
+            restore-keys: |
+              ${{ runner.os }}-node-
+        - name: Install dependencies
+          run: |
+            cd app
+            npm ci
+        - name: Run ESLint
+          run: |
+            cd app
+            if npx ng lint --format summary; then
+              echo "✅ Linting passed - 0 problems" >> $GITHUB_STEP_SUMMARY
+            else
+              echo "❌ Linting failed - see errors above" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
