Updates to do test/lint in the same file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,13 +9,12 @@ on:
     branches:
         - main
         - preview
-
+permissions:
+  contents: read
 jobs:
     test:
         runs-on: ubuntu-latest
         name: Test
-        permissions:
-          contents: read
         steps:
             - name: Checkout code
               uses: actions/checkout@v6
@@ -46,3 +45,26 @@ jobs:
               if: always()
               with:
                 paths: app/test-results/results.xml
+    lint:
+      runs-on: ubuntu-latest
+      steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+      - name: Set up Node.js
+        uses: actions/setup-node@v6
+        with:
+            node-version-file: 'app/.nvmrc'
+      - name: Install dependencies
+        run: |
+          cd app
+          npm ci
+      - name: Run ESLint
+        run: |
+          cd app
+          npm install -g @angular/cli
+          if ng lint --format summary; then
+            echo "✅ Linting passed - 0 problems" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "❌ Linting failed - see errors above" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
